apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: product-namespace
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:productdb"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"